{application,api,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{api_app,[]}},
              {env,[]},
              {modules,[api_app,api_reqest_decode,api_reqest_encode,api_sup,
                        reqest_decode,reqest_encode]}]}.
